global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8080']

  - job_name: 'transfer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transfer-service:8081']
  
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8082']
