spring:
  datasource:
    url: jdbc:postgresql://account-postgres:5432/account_db
    username: account_user
    password: account_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  redis:
    host: account-redis
    port: 6379
  rabbitmq:
    host: arch-rabbitmq
    port: 5672
    username: guest
    password: guest
  amqp:
    deserialization:
      trust:
        all: true
server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
